apiVersion: v1
kind: Service
metadata:
  name: univex-auth-service
spec:
  selector:
    app: univex-auth   # the name of target POD from deployment.yaml
  ports:
  - port: 80  # Expose on port 80
    targetPort: 5050  # Forward to container port 5050
  type: LoadBalancer  # Create a Load Balancer for external access