# Use Node.js 18 runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Expose the port on which your Next.js app will run
ENV PORT 8080
ENV HOST 0.0.0.0
# EXPOSE 3000

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install --only=production
# RUN npm ci

# Copy the source code to the working directory
COPY . .

# Build the Next.js app
RUN npm run build


# Start the Next.js app
CMD [ "npm", "start" ]

